"""Generate the manual-to-automated traceability matrix.

The manual suite lives in an Excel workbook and the automated suite lives in
code. Keeping the mapping in a third place by hand guarantees it goes stale, so
this reads both sides and writes `docs/TRACEABILITY.md`:

- manual case IDs come from the workbook,
- automated coverage comes from the `manual_case` markers on the tests.

Run it after adding or retargeting tests:

    python scripts/traceability.py
"""

from __future__ import annotations

import sys
from collections import defaultdict
from pathlib import Path

import openpyxl

REPO_ROOT = Path(__file__).resolve().parent.parent
WORKBOOK = (
    REPO_ROOT / "SauceDemo_Manual_Test_Cases_Focused_With_Automation_Mapping.xlsx"
)
OUTPUT = REPO_ROOT / "docs" / "TRACEABILITY.md"
CASE_SHEET = "Authentication_Login"


def read_manual_cases() -> list[tuple[str, str, str]]:
    """Return (case id, title, module) for every case in the workbook."""
    workbook = openpyxl.load_workbook(WORKBOOK, data_only=False)
    sheet = workbook[CASE_SHEET]
    rows = list(sheet.iter_rows(values_only=True))

    header_index = next(
        index for index, row in enumerate(rows) if row and row[0] == "Test Case ID"
    )
    columns = {
        name: position for position, name in enumerate(rows[header_index]) if name
    }

    cases = []
    for row in rows[header_index + 1 :]:
        case_id = row[columns["Test Case ID"]]
        if not case_id or not str(case_id).startswith("TC-"):
            continue
        cases.append(
            (
                str(case_id),
                str(row[columns["Test Case Title"]] or ""),
                str(row[columns["Module"]] or ""),
            )
        )
    return cases


def read_automated_coverage() -> dict[str, list[str]]:
    """Map each manual case id to the automated tests that cover it."""
    coverage: dict[str, list[str]] = defaultdict(list)

    # Reading the marker straight from the source keeps this script standalone:
    # it needs no browser, no network and no pytest run to produce the matrix.
    for test_file in sorted((REPO_ROOT / "tests").glob("*.py")):
        pending: list[str] = []
        for line in test_file.read_text(encoding="utf-8").splitlines():
            stripped = line.strip()
            if stripped.startswith("@pytest.mark.manual_case("):
                ids = stripped[len("@pytest.mark.manual_case(") :].rstrip(")")
                pending = [
                    part.strip().strip('"') for part in ids.split(",") if part.strip()
                ]
            elif stripped.startswith("def test_") and pending:
                test_name = stripped[4:].split("(")[0]
                for case_id in pending:
                    coverage[case_id].append(f"{test_file.name}::{test_name}")
                pending = []
    return coverage


def main() -> int:
    cases = read_manual_cases()
    coverage = read_automated_coverage()

    automated = [case for case in cases if case[0] in coverage]
    manual_only = [case for case in cases if case[0] not in coverage]

    orphans = sorted(set(coverage) - {case[0] for case in cases})

    lines = [
        "# Traceability matrix",
        "",
        "Generated by `scripts/traceability.py`. Do not edit by hand.",
        "",
        "Manual case IDs come from the test-case workbook; automated coverage",
        "comes from the `manual_case` markers on the tests themselves, so this",
        "file cannot drift from either side.",
        "",
        "## Summary",
        "",
        "| | Count |",
        "|---|---:|",
        f"| Manual cases in the workbook | {len(cases)} |",
        f"| Covered by automation | {len(automated)} |",
        f"| Manual or exploratory only | {len(manual_only)} |",
        "",
        "## Covered by automation",
        "",
        "| Manual case | Title | Automated test |",
        "|---|---|---|",
    ]
    for case_id, title, _ in automated:
        tests = "<br>".join(f"`{name}`" for name in coverage[case_id])
        lines.append(f"| {case_id} | {title} | {tests} |")

    lines += [
        "",
        "## Not automated",
        "",
        "Retained in the manual and exploratory suite.",
        "",
        "| Manual case | Title | Module |",
        "|---|---|---|",
    ]
    for case_id, title, module in manual_only:
        lines.append(f"| {case_id} | {title} | {module} |")

    if orphans:
        lines += [
            "",
            "## Markers with no matching manual case",
            "",
            "These `manual_case` markers reference ids the workbook does not "
            "contain, which usually means a typo or a removed case.",
            "",
        ]
        lines += [f"- `{case_id}`" for case_id in orphans]

    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(
        f"Wrote {OUTPUT.relative_to(REPO_ROOT)}: "
        f"{len(automated)} of {len(cases)} manual cases automated"
        + (f", {len(orphans)} orphan marker(s)" if orphans else "")
    )
    return 1 if orphans else 0


if __name__ == "__main__":
    sys.exit(main())
